controller_list:
  - name: fake_Arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_pitch_joint
      - elbow_flex_joint
      - wrist_roll_joint
      - left_finger_joint
      - right_finger_joint